name: SFTP Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SFTP Upload
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.USERNAME }}
          server-ip: ${{ secrets.HOST }}
          remote-path: ${{ secrets.TARGET }}
          local-path: "build"  # or "dist" or "build"
          port: ${{ secrets.PORT }}
